const { HTTP_PORT, SECRET_KEY, EXPIRE_TOKEN, MYSQL_HOST, MYSQL_USER, MYSQL_PASS, MYSQL_DB } = process.env;

export { HTTP_PORT, SECRET_KEY, EXPIRE_TOKEN, MYSQL_HOST, MYSQL_USER, MYSQL_PASS, MYSQL_DB };
